language: r
r:
  - oldrel
  - release
  - devel
  
os:
  - linux
  - osx

  
cache: packages

r_github_packages:
  - jimhester/covr
  
warnings_are_errors: true

after_success:
  - Rscript -e 'library(covr); codecov()'
