language: r

r:
  - oldrel
  - release
  - devel
  
  

cache: packages

os:
  - linux

r_github_packages:
  - jimhester/covr

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
