# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

jobs:
  include:
  - r: devel
    env: _R_CHECK_LENGTH_1_LOGIC2_=true
  - r: release
    before_cache:
      - Rscript -e 'remotes::install_cran("pkgdown")'
    after_success:
    - Rscript -e 'covr::codecov()'
    deploy:	
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
    pandoc: false
    env: PANDOC='none'
  - r: oldrel
  - r: 3.3
  - r: 3.4
  - r: 3.5
  - r: 3.6

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=TRUE
