language: r
r:
  - oldrel
  - release
  - devel
  
os:
  - linux

  
cache: packages

r_github_packages:
  - jimhester/covr
  
r_build_args: '--compact-vignettes="gs+qpdf"'


r_check_args: "--as-cran"
  
  
warnings_are_errors: true

after_success:
  - Rscript -e 'library(covr); codecov()'
