on: push

name: revdep

jobs:
  revdep:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: ubuntu-18.04,   r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
  
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.r }}
  
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
  
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}
          
     - name: install libcurl4-openssl-dev for Linux
        run: |
          sudo apt install libcurl4-openssl-dev
  
      - name: Install revdepcheck and run checks
        run: |
          install.packages(c("curl","devtools"),dependencies=TRUE)
          devtools::install_github("r-lib/revdepcheck")
          library(revdepcheck)
          revdep_reset()
          revdep_check(num_workers=4)
        shell: Rscript {0}
          
      
      - name: Upload check results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: revdep/